url: "https://ukah.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "site title" # the name of your site, e.g. ACME Corp.
